CREATE USER IF NOT EXISTS 'exporter'@'%' IDENTIFIED BY 'dipass' WITH MAX_USER_CONNECTIONS 3;
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%';

CREATE USER IF NOT EXISTS 'app'@'%' IDENTIFIED BY 'dipass';
GRANT ALL PRIVILEGES ON *.* TO 'app'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;